### ISSUE TITLE
Snap Package

### ISSUE THREAD

**Issue by arusahni** [arusahni/git-req#29]
It'd be nice to have a Snap package for platforms that don't have an official package.  This isn't as easy as it sounds.

Pro:
* Snap permits packaging of CLI tools.
Con:
* Containment is painful
  * Specifically, one needs to manually connect the `~/.gitreqconfig`,
  * Also, shelling out to git isn't a viable option due to the git binary being outside of the containment.

**Comment by arusahni** [comment]
For reference, here's where I left off during my snap experimentation:

```yaml
name: git-req
version: git
summary: Check out merge requests from your GitLab/GitHub hosted repos with ease!
description: |
  This git extension allows end-users to check out merge requests by
  their corresponding number.

  To use, simply `git req <number>` from the project directory.
confinement: devmode
base: core18
parts:
  git-req:
    plugin: rust
    source: .
    rust-channel: stable
    build-packages:
      - libssl-dev
      - pkg-config
plugs:
  config-git-req:
    interface: personal-files
    read:
      - $HOME/.gitreqconfig # This did not appear to work
    write:
      - $HOME/.gitreqconfig  # This did not appear to work
apps:
  git-req:
    command: bin/git-req
    plugs:
      - network
      - config-git-req
```
